export interface Agent {
  id: string;
  name: string;
  icon: string;
  title: string;
  whenToUse: string;
  squad: string;
}

export interface Squad {
  id: string;
  name: string;
  icon: string;
  agents: Agent[];
}

export const SQUADS: Squad[] = [
  {
    id: 'advisory-board',
    name: 'Advisory Board',
    icon: '🎓',
    agents: [
      { id: 'board-chair', name: 'Board Chair', icon: '🏛️', title: 'Advisory Board Orchestrator — Strategic Facilitation & Wisdom Synthesis', whenToUse: 'When the user needs strategic advice spanning multiple domains. When convening multiple advisors for a board session. When routing questions to the right advisor. When synthesizing conflicting perspectives into actionable guidance.', squad: 'advisory-board' },
      { id: 'brene-brown', name: 'Brene Brown', icon: '💛', title: 'Researcher-Storyteller — Vulnerability, Courage, Shame & Empathic Leadership', whenToUse: 'When the user needs to build trust in teams, navigate shame or fear of failure, develop courageous leadership, foster psychological safety, address conflict avoidance, process difficult emotions, create cultures of belonging, or lead through uncertainty with wholehearted engagement.', squad: 'advisory-board' },
      { id: 'charlie-munger', name: 'Charlie Munger', icon: '🧠', title: 'Multidisciplinary Thinker — Mental Models, Cognitive Bias & Rational Decision-Making', whenToUse: 'When the user needs to think through a problem using multiple mental models simultaneously. When cognitive biases may be distorting judgment. When inversion thinking would reveal hidden risks. When a decision requires brutal intellectual honesty rather than comforting platitudes. When evaluating business quality, competitive moats, or capital allocation.', squad: 'advisory-board' },
      { id: 'derek-sivers', name: 'Derek Sivers', icon: '🎯', title: 'Minimalist Founder — Simplicity, Contrarian Entrepreneurship & Enough', whenToUse: 'When deciding whether to pursue an opportunity (Hell Yeah or No filter). When resisting the pressure to scale, hire, or raise money. When you need to simplify a business, product, or life decision down to its essence. When the conventional path feels wrong and you need permission to go the other way. When struggling with \'enough\' — when to stop growing and start living. When building something solo or with a tiny team. When thinking about ideas vs. execution.', squad: 'advisory-board' },
      { id: 'naval-ravikant', name: 'Naval Ravikant', icon: '🧘', title: 'Philosopher-Investor — Wealth, Leverage & Happiness', whenToUse: 'When you need clarity on wealth creation through leverage and specific knowledge. When evaluating startup ideas or angel investment theses. When thinking about founder-market fit and productizing yourself. When seeking frameworks for happiness, peace of mind, or life design. When deciding between competition and authenticity.', squad: 'advisory-board' },
      { id: 'patrick-lencioni', name: 'Patrick Lencioni', icon: '🏗️', title: 'Master of Organizational Health & Team Dynamics', whenToUse: 'When teams are dysfunctional and trust has eroded. When meetings are painful and unproductive. When leaders struggle with accountability or commitment. When organizational health is suffering despite strategic clarity. When hiring for culture fit. When diagnosing why talented teams underperform. When a leader needs to examine their own motives.', squad: 'advisory-board' },
      { id: 'peter-thiel', name: 'Peter Thiel', icon: '♟️', title: 'Contrarian Venture Philosopher — Monopoly, Secrets & Zero-to-One Thinking', whenToUse: 'When you need contrarian analysis that challenges consensus. When evaluating whether a business creates genuine monopoly value or merely competes. When assessing startup ideas through the Seven Questions framework. When thinking about power laws, secrets, and definite optimism. When the user needs to escape mimetic competition and find what is uniquely true.', squad: 'advisory-board' },
      { id: 'ray-dalio', name: 'Ray Dalio', icon: '📐', title: 'Principles Architect — Systematic Decision-Making, Economic Cycles & Radical Truth', whenToUse: 'When the user needs a systematic framework for making decisions. When facing complex problems that require root-cause diagnosis. When building organizational culture around truth and transparency. When analyzing economic or market cycles. When designing decision-making systems that remove ego and bias. When evaluating risk across portfolios or ventures. When struggling with painful failures and needing to convert them into progress. When building meritocratic teams where the best ideas win.', squad: 'advisory-board' },
      { id: 'reid-hoffman', name: 'Reid Hoffman', icon: '🔗', title: 'Oracle of Networks — Venture Philosophy & Blitzscaling Strategist', whenToUse: 'When you need scaling strategy for a startup, network effects analysis, ABZ career/business planning, alliance-based talent strategy, blitzscaling assessment, or venture-grade thinking about when to prioritize speed over efficiency.', squad: 'advisory-board' },
      { id: 'simon-sinek', name: 'Simon Sinek', icon: '⭕', title: 'Purpose-Driven Leadership & The Infinite Mindset', whenToUse: 'When an organization lacks a clear purpose or WHY. When leaders need to inspire rather than manipulate. When teams lack trust or psychological safety. When facing strategic decisions that need filtering through purpose. When transitioning from finite to infinite thinking. When building culture around a Just Cause. When communication feels rational but uninspiring.', squad: 'advisory-board' },
      { id: 'yvon-chouinard', name: 'Yvon Chouinard', icon: '🏔️', title: 'Reluctant Businessman — Purpose, Planet & Anti-Growth', whenToUse: 'When you need to challenge growth-at-all-costs thinking. When deciding whether to sacrifice short-term profit for long-term integrity. When building a mission-driven company that puts purpose above shareholder returns. When evaluating product quality vs planned obsolescence. When considering environmental responsibility as a business strategy. When struggling with the tension between being a craftsman and being a CEO. When you need someone to tell you the uncomfortable truth about your business.', squad: 'advisory-board' },
    ]
  },
  {
    id: 'brand-squad',
    name: 'Brand Squad',
    icon: '🎨',
    agents: [
      { id: 'al-ries', name: 'Al Ries', icon: '🏔️', title: 'The Father of Positioning — Laws of Marketing & Category Strategy Pioneer', whenToUse: 'When positioning or repositioning a brand. When creating new categories. When applying the 22 Laws of Marketing. When focus and sacrifice decisions are needed. When competitive positioning strategy is required.', squad: 'brand-squad' },
      { id: 'alina-wheeler', name: 'Alina Wheeler', icon: '✏️', title: 'Brand Identity Authority — Five-Phase Process & Designing Brand Identity', whenToUse: 'When designing a complete brand identity system. When following a structured identity process. When evaluating identity against the 9 ideals. When creating brand standards and guidelines. When managing brand touchpoints.', squad: 'brand-squad' },
      { id: 'archetype-consultant', name: 'Archetype Consultant', icon: '🎭', title: 'Brand Personality Architect — Jungian Archetypes & Tone of Voice', whenToUse: 'When defining brand personality. When mapping to archetypes. When creating tone of voice guidelines. When brand expression needs consistency across touchpoints. When brand feels inconsistent or lacks character.', squad: 'brand-squad' },
      { id: 'brand-chief', name: 'Brand Chief', icon: '🎨', title: 'Brand Squad Orchestrator — Strategic Brand Routing Intelligence', whenToUse: 'When any brand-related challenge needs routing to the right specialist. When multiple brand perspectives are needed. When brand strategy requires cross-framework synthesis.', squad: 'brand-squad' },
      { id: 'byron-sharp', name: 'Byron Sharp', icon: '🔬', title: 'Marketing Scientist — Evidence-Based Brand Growth & How Brands Grow', whenToUse: 'When challenging marketing assumptions with evidence. When planning media strategy for brand growth. When debating differentiation vs distinctiveness. When applying evidence-based marketing principles. When reach vs targeting decisions are needed.', squad: 'brand-squad' },
      { id: 'david-aaker', name: 'David Aaker', icon: '👑', title: 'The Father of Modern Branding — Brand Equity & Identity Pioneer', whenToUse: 'When building or measuring brand equity. When defining brand identity/vision. When making brand architecture decisions. When brand relevance and category innovation are needed. When managing brand portfolios.', squad: 'brand-squad' },
      { id: 'denise-yohn', name: 'Denise Lee Yohn', icon: '🔗', title: 'Brand-Culture Fusion Expert — Operationalizing Brand as Business Management', whenToUse: 'When brand and culture are misaligned. When internal branding needs strengthening. When operationalizing brand across the organization. When employee experience needs brand alignment. When building from the inside out.', squad: 'brand-squad' },
      { id: 'domain-scout', name: 'Domain Scout', icon: '🔎', title: 'Digital Naming Viability Specialist — Domain & Handle Strategy', whenToUse: 'When checking domain availability for brand names. When developing domain acquisition strategy. When evaluating TLD alternatives. When ensuring social handle consistency. When digital naming viability is a factor.', squad: 'brand-squad' },
      { id: 'donald-miller', name: 'Donald Miller', icon: '📖', title: 'StoryBrand Creator — SB7 Framework & Clarified Messaging Pioneer', whenToUse: 'When brand messaging is unclear or confusing. When building a BrandScript. When applying story structure to marketing. When creating websites, email sequences, or sales funnels. When the customer needs to be positioned as the hero.', squad: 'brand-squad' },
      { id: 'emily-heyward', name: 'Emily Heyward', icon: '🚀', title: 'Startup Brand Architect — \'Obsessed\' Author & Red Antler Co-Founder', whenToUse: 'When launching a new brand from scratch. When building DTC/startup brands. When brand needs to exist from day one. When emotional branding for new ventures is needed. When naming startups.', squad: 'brand-squad' },
      { id: 'jean-noel-kapferer', name: 'Jean-Noël Kapferer', icon: '💠', title: 'Brand Identity Prism Creator — Strategic Brand & Luxury Management Authority', whenToUse: 'When defining brand identity (not just visual). When applying the Identity Prism. When managing luxury brands. When brand identity vs brand image distinction matters. When brand extension decisions are needed.', squad: 'brand-squad' },
      { id: 'kevin-keller', name: 'Kevin Lane Keller', icon: '📐', title: 'CBBE Pyramid Creator — Strategic Brand Management & Brand Equity Measurement', whenToUse: 'When measuring brand equity. When building the CBBE pyramid (Identity → Meaning → Response → Resonance). When defining brand positioning (POPs, PODs, brand mantras). When conducting brand audits or tracking studies.', squad: 'brand-squad' },
      { id: 'marty-neumeier', name: 'Marty Neumeier', icon: '⚡', title: 'Brand Gap Pioneer — Radical Differentiation & Design Thinking Strategist', whenToUse: 'When radical differentiation is needed. When bridging strategy and creativity. When building the \'onlyness\' statement. When brand feels generic or undifferentiated. When applying design thinking to brand strategy.', squad: 'brand-squad' },
      { id: 'miller-sticky-brand', name: 'Miller Sticky Brand', icon: '📋', title: 'StoryBrand Implementation Engine — BrandScript to Funnel Execution', whenToUse: 'When implementing StoryBrand framework in practice. When creating BrandScripts, one-liners, wireframe websites, lead generators, or email sequences using Miller\'s methodology. When turning StoryBrand theory into actual marketing assets.', squad: 'brand-squad' },
      { id: 'naming-strategist', name: 'Naming Strategist', icon: '💎', title: 'Brand Naming Specialist — Linguistic & Strategic Name Architecture', whenToUse: 'When creating a new brand name. When evaluating existing names. When renaming. When generating name candidates. When checking linguistic and cultural viability.', squad: 'brand-squad' },
    ]
  },
  {
    id: 'c-level-squad',
    name: 'C-Level Squad',
    icon: '👔',
    agents: [
      { id: 'caio-architect', name: 'CAIO Architect', icon: '🤖', title: 'AI Strategy & Intelligent Systems Architecture Specialist', whenToUse: 'When the user needs AI strategy, ML pipeline design, responsible AI governance, AI use case prioritization, LLM integration patterns, AI agent architecture, AI ROI analysis, or AI team structure decisions. When the company wants to leverage AI but doesn\'t know where to start or how to do it responsibly. When AI investments need to translate into measurable business outcomes.', squad: 'c-level-squad' },
      { id: 'cio-engineer', name: 'CIO Engineer', icon: '🖥️', title: 'Information Systems & Digital Infrastructure Specialist', whenToUse: 'When the user faces information systems challenges — enterprise architecture decisions, security posture assessment, compliance requirements (SOC2, GDPR, HIPAA), vendor evaluation, IT governance, digital transformation strategy, system integration, or data infrastructure design. When the company needs to professionalize its IT operations.', squad: 'c-level-squad' },
      { id: 'cmo-architect', name: 'CMO Architect', icon: '📣', title: 'Marketing Strategy & Brand Architecture Specialist', whenToUse: 'When the user needs brand positioning, go-to-market strategy, demand generation architecture, marketing measurement frameworks, customer acquisition strategy, or brand architecture decisions. When marketing feels random instead of systematic. When the brand message isn\'t landing.', squad: 'c-level-squad' },
      { id: 'coo-orchestrator', name: 'COO Orchestrator', icon: '⚙️', title: 'Operational Excellence & Scaling Specialist', whenToUse: 'When the user faces operational challenges — scaling bottlenecks, broken processes, team structure problems, unclear KPIs, resource misallocation, or OKR design. When the company is growing faster than its systems. When the founder needs to stop being the bottleneck.', squad: 'c-level-squad' },
      { id: 'cto-architect', name: 'CTO Architect', icon: '🔧', title: 'Technology Strategy & Engineering Leadership Specialist', whenToUse: 'When the user faces technology strategy decisions — architecture choices, build vs buy, technical debt management, engineering team structure, innovation roadmap, technology evaluation, or engineering culture challenges. When technology needs to be a competitive moat, not just infrastructure.', squad: 'c-level-squad' },
      { id: 'vision-chief', name: 'Vision Chief', icon: '👔', title: 'Strategic Vision & Executive Leadership Orchestrator', whenToUse: 'When the user needs holistic CEO-level strategic counsel. When routing complex business challenges to the right C-level executive perspective. When synthesizing multi-functional executive insights into unified company strategy. When addressing vision, fundraising, culture, board, or existential company decisions.', squad: 'c-level-squad' },
    ]
  },
  {
    id: 'claude-code-mastery',
    name: 'Claude Code',
    icon: '💻',
    agents: [
      { id: 'claude-mastery-chief', name: 'claude-mastery-chief', icon: '\U0001F9E0', title: '', whenToUse: '', squad: 'claude-code-mastery' },
      { id: 'config-engineer', name: 'config-engineer', icon: '\u2699\uFE0F', title: '', whenToUse: '', squad: 'claude-code-mastery' },
      { id: 'hooks-architect', name: 'hooks-architect', icon: '\U0001F3A3', title: '', whenToUse: '', squad: 'claude-code-mastery' },
      { id: 'mcp-integrator', name: 'mcp-integrator', icon: '\U0001F50C', title: '', whenToUse: '', squad: 'claude-code-mastery' },
      { id: 'project-integrator', name: 'project-integrator', icon: '\U0001F6E0\uFE0F', title: '', whenToUse: '', squad: 'claude-code-mastery' },
      { id: 'roadmap-sentinel', name: 'roadmap-sentinel', icon: '\U0001F9ED', title: '', whenToUse: '', squad: 'claude-code-mastery' },
      { id: 'skill-craftsman', name: 'skill-craftsman', icon: '\u2728', title: '', whenToUse: '', squad: 'claude-code-mastery' },
      { id: 'swarm-orchestrator', name: 'swarm-orchestrator', icon: '🤖', title: 'Topology Recommendation', whenToUse: '', squad: 'claude-code-mastery' },
    ]
  },
  {
    id: 'copy-squad',
    name: 'Copy Squad',
    icon: '✍️',
    agents: [
      { id: 'andre-chaperon', name: 'Andre Chaperon', icon: '✉️', title: 'The Quiet Master of Email Storytelling & the Soap Opera Sequence', whenToUse: 'When building email sequences that nurture deeply. When emails feel transactional and need soul. When writing soap opera sequences, autoresponder series, or any email that must build intimate trust over time. When you need open loops and story arcs in email.', squad: 'copy-squad' },
      { id: 'ben-settle', name: 'Ben Settle', icon: '📧', title: 'The Anti-Guru Email Maverick — Daily Emails & Personality-First Copy', whenToUse: 'When you need daily email strategies. When copy lacks personality and entertainment value. When you want to build a loyal audience through polarization. When email sequences feel generic and lifeless. When you need the \'infotainment\' approach.', squad: 'copy-squad' },
      { id: 'claude-hopkins', name: 'Claude Hopkins', icon: '🔬', title: 'Father of Scientific Advertising', whenToUse: 'When you need a data-driven, testing-first approach to copy. When copy needs to be stripped of ego and focused purely on selling. When you need to evaluate ads by results, not opinions.', squad: 'copy-squad' },
      { id: 'clayton-makepeace', name: 'Clayton Makepeace', icon: '💰', title: 'The Highest-Paid Copywriter — Emotional Selling & the Four-Legged Stool', whenToUse: 'When copy needs emotional power grounded in proof. When writing financial or health promotions. When the Four-Legged Stool is incomplete. When you need to identify and amplify Dominant Resident Emotions. When pricing strategy matters.', squad: 'copy-squad' },
      { id: 'copy-chief', name: 'Copy Chief', icon: '✍️', title: 'Copy Chief — Squad Orchestrator', whenToUse: 'Activate when the user needs copywriting help but hasn\'t specified which specialist to use, or when a project requires multiple copywriters working together.', squad: 'copy-squad' },
      { id: 'dan-kennedy', name: 'Dan Kennedy', icon: '🎯', title: 'The Professor of Harsh Reality — No B.S. Direct Response', whenToUse: 'When you need no-nonsense business advice, offer creation, sales letters, pricing strategy, direct mail campaigns, info-marketing systems, or someone to cut through excuses and focus on what actually makes money.', squad: 'copy-squad' },
      { id: 'dan-koe', name: 'Dan Koe', icon: '🧘', title: 'The One-Person Business Philosopher — Deep Generalism & Creator Economy', whenToUse: 'When writing short-form content that must stop the scroll. When building personal brand copy. When creating newsletter content systems. When applying philosophical depth to marketing. When building a One-Person Business content ecosystem.', squad: 'copy-squad' },
      { id: 'david-deutsch', name: 'David Deutsch', icon: '🧩', title: 'The CopyTHINKING Expert — Big Ideas & Fascination Master', whenToUse: 'When copy needs a stronger Big Idea. When you need world-class fascination bullets. When the THINKING behind the copy is weak — not the writing. When you need to apply fiction techniques to sales copy. When generating multiple headline approaches.', squad: 'copy-squad' },
      { id: 'david-ogilvy', name: 'David Ogilvy', icon: '🎩', title: 'Father of Modern Advertising', whenToUse: 'When you need brand-level copywriting, luxury/premium positioning, research-backed creative, long-form factual persuasion, or a Big Idea to unify a campaign.', squad: 'copy-squad' },
      { id: 'eugene-schwartz', name: 'Eugene Schwartz', icon: '🧠', title: 'Master of Market Awareness & Strategic Copy', whenToUse: 'When you need to diagnose market awareness levels, craft headlines for any awareness stage, navigate saturated markets, or apply the most systematic framework to any copywriting challenge.', squad: 'copy-squad' },
      { id: 'frank-kern', name: 'Frank Kern', icon: '🏄', title: 'The Intent-Based Branding Pioneer — Results In Advance', whenToUse: 'When you need intent-based branding strategy, behavioral email sequences, Results In Advance positioning, webinar/launch sequences, or when copy needs to feel authentic and valuable rather than salesy. When building goodwill-first marketing systems.', squad: 'copy-squad' },
      { id: 'gary-bencivenga', name: 'Gary Bencivenga', icon: '👑', title: 'The World\'s Greatest Living Copywriter — Master of Proof', whenToUse: 'When copy needs bulletproof proof elements. When claims feel unbelievable. When you need the \'Persuasion Equation.\' When copy has hype but no credibility. When writing for sophisticated, skeptical audiences. When you need the absolute highest-level direct response copy.', squad: 'copy-squad' },
      { id: 'gary-halbert', name: 'Gary Halbert', icon: '🔥', title: 'The Prince of Print — Raw Emotional Storytelling & Street Marketing', whenToUse: 'When copy lacks raw emotional power. When you need street-smart marketing advice. When the offer needs a starving crowd. When copy is too polished and needs grit. When writing sales letters, direct mail, or any persuasion piece that must grab by the throat and not let go.', squad: 'copy-squad' },
      { id: 'jim-rutz', name: 'Jim Rutz', icon: '📰', title: 'The Copywriter Closest to God — Magalog Pioneer & Anti-Bore Crusader', whenToUse: 'When copy is boring and predictable. When you need innovative formats (magalogs, bookalogs). When copy needs wit, humor, and fearless creativity. When writing long-form health or financial promotions. When you need to surprise the reader at every turn.', squad: 'copy-squad' },
      { id: 'joe-sugarman', name: 'Joe Sugarman', icon: '🕶️', title: 'The Slippery Slide Master — Psychological Triggers & Print Advertising Pioneer', whenToUse: 'When copy doesn\'t flow — readers stop mid-way. When you need psychological triggers to increase conversion. When writing print ads, product launch copy, or direct response ads. When copy needs to be a \'slippery slide\' that readers can\'t stop reading.', squad: 'copy-squad' },
      { id: 'john-carlton', name: 'John Carlton', icon: '🕵️', title: 'The Sales Detective — Most Ripped-Off Copywriter Alive', whenToUse: 'When copy needs raw selling power with entertainment value. When you need to uncover the hidden selling angle. When copy is boring, safe, or predictable. When you need the \'Simple Writing System.\' When freelancers need career and copy advice.', squad: 'copy-squad' },
      { id: 'jon-benson', name: 'Jon Benson', icon: '🎬', title: 'The VSL Inventor — Billion Dollar Copywriter & NLP Master', whenToUse: 'When writing Video Sales Letters (VSLs). When you need the 5-Step VSL Formula. When copy needs NLP techniques (presupposition, pattern interrupt, future pacing). When creating unique mechanisms for offers. When writing email copy using the EPIC framework.', squad: 'copy-squad' },
      { id: 'parris-lampropoulos', name: 'Parris Lampropoulos', icon: '🎯', title: 'The Best Copywriter You Never Heard Of — Master of Fascinations & Format', whenToUse: 'When writing long-form health, financial, or tax promotions. When fascination bullets need to be world-class. When the format is wrong for the audience. When you need to beat an existing control. When research depth is insufficient.', squad: 'copy-squad' },
      { id: 'robert-collier', name: 'Robert Collier', icon: '💌', title: 'Master of Empathy & the Mental Movie', whenToUse: 'When copy feels disconnected from the audience. When you need emotional connection before selling. When the opening is weak or product-focused. When copy is too abstract and needs vivid imagery. When writing follow-up sequences.', squad: 'copy-squad' },
      { id: 'russell-brunson', name: 'Russell Brunson', icon: '🔻', title: 'The Funnel Architect — Value Ladders, Hooks & Epiphany Bridges', whenToUse: 'When building sales funnels, webinar scripts, launch sequences, or lead magnets. When you need Value Ladder strategy, Hook-Story-Offer framework, or Epiphany Bridge storytelling. When you need to structure an entire customer journey from first click to high-ticket.', squad: 'copy-squad' },
      { id: 'ry-schwartz', name: 'Ry Schwartz', icon: '🎭', title: 'The Conversion Coach — Belief Transformation & Launch Email Master', whenToUse: 'When writing launch email sequences. When copy feels manipulative and needs an ethical coaching approach. When you need belief transformation strategy. When writing for course creators, coaches, and consultants. When closing sequences need to coach decisiveness, not pressure purchases.', squad: 'copy-squad' },
      { id: 'stefan-georgi', name: 'Stefan Georgi', icon: '⚙️', title: 'The RMBC Architect — $700M in Systematic Copy', whenToUse: 'When you need a systematic, repeatable process for writing copy. When writing VSLs or long-form sales pages. When the copy needs a unique mechanism. When research is inadequate. When you need the RMBC Method.', squad: 'copy-squad' },
      { id: 'todd-brown', name: 'Todd Brown', icon: '💡', title: 'The Marketer\'s Marketer — Big Ideas & Unique Mechanisms', whenToUse: 'When you need a Big Marketing Idea for a campaign. When the offer has no unique mechanism. When funnel conversion is stalling because the CONCEPT is weak. When you need the E5 Method for campaign architecture.', squad: 'copy-squad' },
    ]
  },
  {
    id: 'cybersecurity',
    name: 'Cybersecurity',
    icon: '🔒',
    agents: [
      { id: 'busterer', name: 'Busterer', icon: '🔍', title: 'Web Content Discovery & Endpoint Enumeration Specialist', whenToUse: 'When discovering hidden web content. When enumerating directories and files on web servers. When finding virtual hosts. When mapping API endpoints. When looking for backup files, config files, or admin panels.', squad: 'cybersecurity' },
      { id: 'cartographer', name: 'Cartographer', icon: '🗺️', title: 'Reconnaissance & Attack Surface Mapping Specialist', whenToUse: 'When mapping a target\'s attack surface. When performing network reconnaissance. When building infrastructure topology maps. When identifying all entry points before an assessment.', squad: 'cybersecurity' },
      { id: 'chris-sanders', name: 'Chris Sanders', icon: '📡', title: 'Network Security Monitoring & Investigation Theory Expert', whenToUse: 'When analyzing network traffic and packets. When setting up network security monitoring. When investigating security incidents. When building SOC practices. When deploying intrusion detection systems or honeypots. When teaching investigation methodology.', squad: 'cybersecurity' },
      { id: 'command-generator', name: 'Command Generator', icon: '⚡', title: 'Security Tool Command Specialist — Precise Syntax Generation for Offensive & Defensive Tools', whenToUse: 'When the user needs exact command syntax for security tools. When translating a security objective into tool commands. When building tool chains for assessments. When explaining tool options and flags.', squad: 'cybersecurity' },
      { id: 'cyber-chief', name: 'Cyber Chief', icon: '🛡️', title: 'Cybersecurity Operations Orchestrator — Threat Assessment, Team Coordination & Ethical Oversight', whenToUse: 'When the user needs cybersecurity guidance spanning multiple domains. When routing to the right offensive or defensive specialist. When coordinating a full security assessment. When ensuring ethical boundaries are maintained.', squad: 'cybersecurity' },
      { id: 'dirber', name: 'Dirber', icon: '📂', title: 'Network Service Enumeration Specialist — SMB, LDAP, SNMP, RPC & Beyond', whenToUse: 'When enumerating network services beyond web. When extracting information from SMB, LDAP, SNMP, NFS, RPC. When mapping Active Directory. When finding shares, users, groups, and policies on a network.', squad: 'cybersecurity' },
      { id: 'fuzzer', name: 'Fuzzer', icon: '🎯', title: 'Input Fuzzing & Parameter Manipulation Specialist', whenToUse: 'When testing application inputs for vulnerabilities. When fuzzing parameters, headers, cookies. When looking for injection points. When testing API endpoints. When performing boundary testing.', squad: 'cybersecurity' },
      { id: 'georgia-weidman', name: 'Georgia Weidman', icon: '📱', title: 'Mobile Security & Penetration Testing Expert — Hands-On Education & Exploit Development', whenToUse: 'When testing mobile device security. When learning penetration testing fundamentals. When integrating mobile devices into security assessments. When developing exploits. When needing practical, beginner-friendly security guidance.', squad: 'cybersecurity' },
      { id: 'jim-manico', name: 'Jim Manico', icon: '🔒', title: 'Application Security & Secure Coding Expert — OWASP Leadership & Developer Education', whenToUse: 'When securing web applications. When implementing OWASP best practices. When reviewing code for security vulnerabilities. When designing authentication and authorization systems. When preventing injection attacks, XSS, and other OWASP Top 10 issues.', squad: 'cybersecurity' },
      { id: 'marcus-carey', name: 'Marcus Carey', icon: '🎯', title: 'Security Leadership, Threat Intelligence & Community Wisdom Expert', whenToUse: 'When building and leading security teams. When developing threat intelligence programs. When needing career guidance in cybersecurity. When planning breach and attack simulation. When seeking diverse perspectives on security strategy.', squad: 'cybersecurity' },
      { id: 'omar-santos', name: 'Omar Santos', icon: '🎖️', title: 'Vulnerability Management, Incident Response & AI Security Expert', whenToUse: 'When managing vulnerabilities and CVEs. When responding to security incidents. When building cybersecurity programs and policies. When needing Cisco security expertise. When working with security standards (CSAF, VEX, SBOM). When addressing AI security.', squad: 'cybersecurity' },
      { id: 'peter-kim', name: 'Peter Kim', icon: '🏈', title: 'Red Team Operations & Penetration Testing Methodology Expert', whenToUse: 'When planning penetration tests or red team engagements. When needing step-by-step attack methodology. When learning offensive security techniques. When building attack playbooks. When mapping techniques to MITRE ATT&CK.', squad: 'cybersecurity' },
      { id: 'ripper', name: 'Ripper', icon: '🔓', title: 'Credential Cracking & Password Security Assessment Specialist', whenToUse: 'When cracking password hashes. When assessing password policy strength. When building targeted wordlists. When analyzing credential dumps. When performing offline password attacks.', squad: 'cybersecurity' },
      { id: 'rogue', name: 'Rogue', icon: '💀', title: 'Exploitation & Post-Exploitation Specialist — Controlled Impact Demonstration', whenToUse: 'When exploiting confirmed vulnerabilities. When demonstrating impact of findings. When performing post-exploitation (privilege escalation, lateral movement, persistence). When building exploit chains. When operating in CTF environments.', squad: 'cybersecurity' },
      { id: 'shannon-runner', name: 'Shannon Runner', icon: '🔎', title: 'OSINT Collection & Analysis Specialist — Open Source Intelligence Operations', whenToUse: 'When gathering intelligence from public sources. When profiling organizations or individuals for authorized assessments. When performing social engineering reconnaissance. When building target dossiers from open data.', squad: 'cybersecurity' },
    ]
  },
  {
    id: 'data-squad',
    name: 'Data Squad',
    icon: '📊',
    agents: [
      { id: 'avinash-kaushik', name: 'Avinash Kaushik', icon: '🔍', title: 'Digital Marketing Evangelist & Web Analytics Authority', whenToUse: 'When you need to build a measurement model, set up actionable KPIs, create dashboards that drive decisions, diagnose why analytics isn\'t working, challenge vanity metrics, or apply the See-Think-Do-Care framework to any digital strategy.', squad: 'data-squad' },
      { id: 'data-chief', name: 'Data Chief', icon: '📊', title: 'Data Chief — Data-Driven Growth Operations Orchestrator', whenToUse: 'Activate when the user needs data analysis, growth strategy, retention insights, community metrics, or customer analytics but hasn\'t specified which specialist to use, or when a project requires multiple data specialists working together.', squad: 'data-squad' },
      { id: 'david-spinks', name: 'David Spinks', icon: '🤝', title: 'Community Strategy Pioneer & Community-Led Growth Expert', whenToUse: 'When building community strategy from scratch. When measuring community ROI and connecting it to business outcomes. When designing community engagement programs. When evaluating community platforms. When building community-led growth motions. When applying the SPACES model to understand community business value.', squad: 'data-squad' },
      { id: 'nick-mehta', name: 'Nick Mehta', icon: '💚', title: 'Customer Success Pioneer & Net Revenue Retention Evangelist', whenToUse: 'When building customer success strategy and operations. When designing health scores and early warning systems for churn. When optimizing Net Revenue Retention (NRR). When building onboarding programs. When defining CS team structure, metrics, and maturity. When making the business case for investing in post-sale customer experience.', squad: 'data-squad' },
      { id: 'peter-fader', name: 'Peter Fader', icon: '💎', title: 'Customer Lifetime Value Authority & Customer Centricity Pioneer', whenToUse: 'When you need to calculate customer lifetime value, build customer segmentation by value, challenge \'all customers are equal\' thinking, apply probability models to customer behavior, evaluate customer-based corporate valuation, or build a customer-centric strategy grounded in data.', squad: 'data-squad' },
      { id: 'sean-ellis', name: 'Sean Ellis', icon: '🚀', title: 'Growth Hacking Pioneer & Product-Market Fit Expert', whenToUse: 'When you need to validate product-market fit, design growth experiments, build a growth machine, set up North Star Metrics, create ICE-scored experiment pipelines, optimize activation/retention/referral, or diagnose why growth has stalled.', squad: 'data-squad' },
      { id: 'wes-kao', name: 'Wes Kao', icon: '🎓', title: 'Cohort-Based Education & Audience Building Strategist', whenToUse: 'When designing cohort-based courses or educational products. When building audience and personal brand strategy. When creating content with a spiky point of view. When measuring educational product metrics (completion, NPS, engagement). When thinking about creator economy strategy, rigorous thinking, or executive communication.', squad: 'data-squad' },
    ]
  },
  {
    id: 'design-squad',
    name: 'Design Squad',
    icon: '🖌️',
    agents: [
      { id: 'brad-frost', name: 'Brad Frost', icon: '⚛️', title: 'Atomic Design & Design Systems Methodology Expert', whenToUse: 'When building design systems from scratch. When applying atomic design methodology. When creating component libraries and pattern labs. When bridging design and development. When establishing design system governance.', squad: 'design-squad' },
      { id: 'dan-mall', name: 'Dan Mall', icon: '🎯', title: 'Design Systems at Scale & Creative Direction Expert', whenToUse: 'When scaling design systems across organizations. When establishing design system governance and adoption. When planning creative direction. When improving designer-developer collaboration. When building design system business cases.', squad: 'design-squad' },
      { id: 'dave-malouf', name: 'Dave Malouf', icon: '⚙️', title: 'DesignOps Pioneer & Design Leadership Expert', whenToUse: 'When establishing DesignOps practices. When managing design teams at scale. When optimizing design processes and workflows. When assessing design maturity. When defending design value in agile environments. When building design culture.', squad: 'design-squad' },
      { id: 'design-chief', name: 'Design Chief', icon: '🎨', title: 'Design Operations Orchestrator — Design Systems, UX & Visual Design Coordination', whenToUse: 'When the user needs design guidance spanning multiple domains. When routing to the right design specialist. When coordinating design system creation or UX research projects. When ensuring design consistency across a product.', squad: 'design-squad' },
      { id: 'design-system-architect', name: 'Design System Architect', icon: '🧩', title: 'Component Library & Design Token Implementation Specialist', whenToUse: 'When building component libraries. When implementing design tokens. When defining component APIs. When creating design system documentation. When auditing design system consistency.', squad: 'design-squad' },
      { id: 'ui-engineer', name: 'UI Engineer', icon: '💻', title: 'Frontend UI Implementation & Production Code Specialist', whenToUse: 'When implementing UI designs in code. When building responsive layouts. When creating interactive components. When optimizing frontend performance. When implementing animations and transitions.', squad: 'design-squad' },
      { id: 'ux-designer', name: 'UX Designer', icon: '👤', title: 'User Experience Research & Interaction Design Specialist', whenToUse: 'When conducting user research. When designing information architecture. When creating wireframes and user flows. When planning usability tests. When ensuring accessibility compliance. When mapping user journeys.', squad: 'design-squad' },
      { id: 'visual-generator', name: 'Visual Generator', icon: '🖼️', title: 'Visual Asset Creation & AI Image Prompt Specialist', whenToUse: 'When generating visual concepts and AI image prompts. When creating thumbnails, icons, or illustrations. When defining visual identity and brand aesthetics. When producing brand-aligned creative assets.', squad: 'design-squad' },
    ]
  },
  {
    id: 'hormozi-squad',
    name: 'Hormozi Squad',
    icon: '💰',
    agents: [
      { id: 'hormozi-ads', name: 'Hormozi Ads', icon: '📢', title: 'Paid Advertising Strategy — Hormozi Framework', whenToUse: 'When paid ads aren\'t profitable. When CPA is too high. When creative is fatiguing. When scaling ad spend. When choosing ad platforms. When building ad funnels.', squad: 'hormozi-squad' },
      { id: 'hormozi-advisor', name: 'Hormozi Advisor', icon: '🦁', title: 'Strategic Business Advisor — The Hormozi Voice', whenToUse: 'When needing strategic business advice. When stuck at a plateau. When making business model decisions. When unsure what to focus on. When wanting \'What would Hormozi do?\' perspective.', squad: 'hormozi-squad' },
      { id: 'hormozi-audit', name: 'Hormozi Audit', icon: '🔍', title: 'Business Evaluation & Improvement Diagnostician', whenToUse: 'When evaluating a business. When doing a health check. When identifying what\'s broken. When preparing for investment or sale. When benchmarking performance.', squad: 'hormozi-squad' },
      { id: 'hormozi-chief', name: 'Hormozi Chief', icon: '🐝', title: 'Hormozi Squad Orchestrator', whenToUse: '', squad: 'hormozi-squad' },
      { id: 'hormozi-closer', name: 'Hormozi Closer', icon: '🤝', title: 'CLOSER Framework & Sales Process Specialist', whenToUse: 'When leads don\'t convert. When sales cycle is too long. When closing rate is low. When objection handling is weak. When building sales scripts. When training sales teams. When reducing no-show rates.', squad: 'hormozi-squad' },
      { id: 'hormozi-content', name: 'Hormozi Content', icon: '📱', title: 'Content Machine & Organic Strategy Specialist', whenToUse: 'When organic leads are weak. When content isn\'t converting. When building a content system. When choosing platforms. When building authority through content. When repurposing content.', squad: 'hormozi-squad' },
      { id: 'hormozi-copy', name: 'Hormozi Copy', icon: '✍️', title: 'Hormozi-Style Copywriting Specialist', whenToUse: 'When writing sales pages, landing pages, or ad copy in Hormozi\'s direct style. When copy needs to be value-driven, not hype-driven. When writing offer descriptions, bonus stacks, or guarantee sections.', squad: 'hormozi-squad' },
      { id: 'hormozi-hooks', name: 'Hormozi Hooks', icon: '🪝', title: 'Hook Creation & Attention Capture Specialist', whenToUse: 'When content isn\'t getting engagement. When emails aren\'t being opened. When ads aren\'t clicking. When needing headlines, subject lines, or opening lines. When scroll-stopping power is needed.', squad: 'hormozi-squad' },
      { id: 'hormozi-launch', name: 'Hormozi Launch', icon: '🚀', title: 'Launch Strategy & Market Entry Specialist', whenToUse: 'When launching a new product. When entering a new market. When starting from zero. When doing a pre-sale. When building a waitlist. When planning a beta launch.', squad: 'hormozi-squad' },
      { id: 'hormozi-leads', name: 'Hormozi Leads', icon: '🧲', title: '$100M Leads Specialist — Core 4 Lead Generation', whenToUse: 'When not enough leads. When pipeline is inconsistent. When scaling acquisition. When building lead magnets. When choosing between outreach channels. When lead cost is too high.', squad: 'hormozi-squad' },
      { id: 'hormozi-models', name: 'Hormozi Models', icon: '🏗️', title: 'Business Model Selection & Design Specialist', whenToUse: 'When the business model is wrong. When margins are too thin. When the model can\'t scale. When choosing between business models. When designing revenue architecture.', squad: 'hormozi-squad' },
      { id: 'hormozi-offers', name: 'Hormozi Offers', icon: '🎰', title: 'Grand Slam Offer Architect', whenToUse: 'When creating or improving offers. When conversion is low. When people say \'too expensive.\' When there\'s no differentiation. When building guarantees. When stacking bonuses. When naming offers.', squad: 'hormozi-squad' },
      { id: 'hormozi-pricing', name: 'Hormozi Pricing', icon: '💎', title: 'Value-Based Pricing Strategist', whenToUse: 'When competing on price. When margins are thin. When can\'t charge enough. When pricing a new offer. When customers say \'too expensive.\' When building premium positioning.', squad: 'hormozi-squad' },
      { id: 'hormozi-retention', name: 'Hormozi Retention', icon: '🔄', title: 'Churn Reduction & Lifetime Value Maximization', whenToUse: 'When churn is high. When LTV is low. When customers leave after 1-3 months. When onboarding is weak. When needing retention systems. When building ascension models.', squad: 'hormozi-squad' },
      { id: 'hormozi-scale', name: 'Hormozi Scale', icon: '📈', title: 'Business Scaling & Systems Specialist', whenToUse: 'When stuck at a revenue plateau. When owner is the bottleneck. When operations are breaking. When hiring and delegation fails. When transitioning from operator to CEO.', squad: 'hormozi-squad' },
      { id: 'hormozi-workshop', name: 'Hormozi Workshop', icon: '🎓', title: 'Workshop Design & Delivery Specialist', whenToUse: 'When designing workshops or events. When creating group training. When building premium experiences. When using workshops as sales vehicles. When creating intensives or masterminds.', squad: 'hormozi-squad' },
    ]
  },
  {
    id: 'movement',
    name: 'Movement',
    icon: '🌊',
    agents: [
      { id: 'analista-de-impacto', name: 'Analista de Impacto', icon: '📊', title: 'Impact Measurement & Movement Health Specialist', whenToUse: 'When measuring whether a movement is creating real change or just generating attention. When designing impact measurement frameworks. When diagnosing movement health. When evaluating community vitality. When building social proof from real outcomes. When tracking the ripple effects of movement activity. When a movement needs to prove its impact to stakeholders, allies, or itself.', squad: 'movement' },
      { id: 'estrategista-de-ciclo', name: 'Estrategista de Ciclo', icon: '🔄', title: 'Growth Cycle Strategy & Movement Momentum Specialist', whenToUse: 'When designing the growth engine for a movement — attract, activate, sustain, multiply. When a movement has identity but lacks growth mechanics. When momentum is stalling or growth is plateauing. When designing activation sequences for new members. When planning multiplication strategies for committed members. When optimizing the flywheel between phases.', squad: 'movement' },
      { id: 'fenomenologo', name: 'Fenomenologo', icon: '🔮', title: 'Phenomenological Analysis & Shared Experience Specialist', whenToUse: 'When identifying the core tension that could fuel a movement. When analyzing shared human experiences, frustrations, and aspirations. When testing whether an idea resonates with lived reality. When mapping the emotional landscape of a community. When a movement needs to reconnect with its original felt truth.', squad: 'movement' },
      { id: 'identitario', name: 'Identitario', icon: '🛡️', title: 'Identity Architecture & Tribal Formation Specialist', whenToUse: 'When designing the identity system for a movement — values, beliefs, symbols, language, rituals, boundaries. When defining who the movement is for and who it is not for. When a movement needs clearer tribal markers. When internal fragmentation threatens cohesion. When translating a felt tension into a shared identity that people can wear, speak, and embody.', squad: 'movement' },
      { id: 'manifestador', name: 'Manifestador', icon: '📜', title: 'Manifesto Creation & Narrative Propagation Specialist', whenToUse: 'When a movement needs its founding document — manifesto, declaration, creed, or founding narrative. When existing narrative is not spreading or not converting. When the movement\'s words do not match its identity. When designing narrative propagation strategy. When a movement needs to re-articulate its beliefs for a new phase or audience.', squad: 'movement' },
      { id: 'movement-architect', name: 'Movement Architect', icon: '🏗️', title: 'Movement Architecture & Community Design Specialist', whenToUse: 'When designing community structures for a movement. When building engagement ladders and participation pathways. When creating governance models for decentralized communities. When designing rituals, gatherings, and recurring experiences. When a movement needs structural engineering to sustain growth.', squad: 'movement' },
      { id: 'movement-chief', name: 'Movement Chief', icon: '✊', title: 'Movement Building Operations Orchestrator', whenToUse: 'When a user wants to build, analyze, or scale a movement. When multiple movement-building disciplines need coordination. When routing movement requests across strategy and execution. When assessing whether an idea has movement potential.', squad: 'movement' },
    ]
  },
  {
    id: 'storytelling',
    name: 'Storytelling',
    icon: '📖',
    agents: [
      { id: 'blake-snyder', name: 'Blake Snyder', icon: '🎬', title: 'Save the Cat Beat Sheet Creator — Commercial Story Structure Master', whenToUse: 'When structuring a screenplay or novel. When applying the 15-beat sheet. When classifying stories by genre type. When crafting loglines. When commercial story structure is needed. When using The Board method.', squad: 'storytelling' },
      { id: 'dan-harmon', name: 'Dan Harmon', icon: '🔄', title: 'Story Circle Creator — TV Writing & Practical Narrative Structure', whenToUse: 'When structuring TV episodes, series, or any episodic content. When applying the Story Circle (8 steps). When story structure needs to be practical and accessible. When understanding fractal narrative (circles within circles). When unblocking creative work.', squad: 'storytelling' },
      { id: 'joseph-campbell', name: 'Joseph Campbell', icon: '🏛️', title: 'Monomyth Creator — Comparative Mythology & The Hero\'s Journey', whenToUse: 'When exploring universal story patterns. When building mythic narrative structure. When applying the Hero\'s Journey (17 stages). When understanding archetypes. When connecting personal story to universal patterns. When mythology meets psychology.', squad: 'storytelling' },
      { id: 'keith-johnstone', name: 'Keith Johnstone', icon: '🎭', title: 'Impro & Theatresports Creator — Spontaneity, Status & Improvised Narrative', whenToUse: 'When creative blocks need breaking. When understanding status dynamics. When improvisation and spontaneity are needed. When \'Yes, And\' thinking is required. When fear of failure is killing creativity.', squad: 'storytelling' },
      { id: 'kindra-hall', name: 'Kindra Hall', icon: '💎', title: 'Business Storytelling Strategist — 4 Stories Framework & Stories That Stick', whenToUse: 'When business needs strategic stories (sales, marketing, leadership). When identifying Story Gaps. When crafting Value, Founder, Purpose, or Customer stories. When personal narratives need to drive business results.', squad: 'storytelling' },
      { id: 'marshall-ganz', name: 'Marshall Ganz', icon: '✊', title: 'Public Narrative Creator — Organizing, Leadership & Movement Storytelling', whenToUse: 'When narrative is needed for social change or collective action. When building public narrative (Self, Us, Now). When organizing communities. When values must translate into action. When leadership communication needs moral authority.', squad: 'storytelling' },
      { id: 'matthew-dicks', name: 'Matthew Dicks', icon: '🎤', title: 'Storyworthy Methodology Creator — Personal Storytelling & The Moth Champion', whenToUse: 'When finding and crafting personal stories. When the five-second moment is needed. When vulnerability and authenticity matter. When practicing Homework for Life. When stories need emotional truth over spectacle.', squad: 'storytelling' },
      { id: 'nancy-duarte', name: 'Nancy Duarte', icon: '📊', title: 'Presentation Storytelling Authority — Sparkline Creator & Visual Narrative Master', whenToUse: 'When designing presentations or keynotes. When applying the Sparkline structure. When turning data into narrative. When the audience must be moved to action. When visual storytelling is needed.', squad: 'storytelling' },
      { id: 'oren-klaff', name: 'Oren Klaff', icon: '🎲', title: 'Pitch Anything Creator — Frame Control, Neurofinance & High-Stakes Persuasion', whenToUse: 'When pitching to investors, clients, or decision-makers. When frame control is needed. When understanding the croc brain matters. When high-stakes persuasion is required. When the pitch dynamic needs to be flipped.', squad: 'storytelling' },
      { id: 'park-howell', name: 'Park Howell', icon: '🎯', title: 'ABT & Story Cycle Creator — Business Storytelling Strategist', whenToUse: 'When brand storytelling is needed. When applying ABT (And, But, Therefore). When building a brand Story Cycle. When business communication needs narrative structure. When replacing \'death by bullet points.\'', squad: 'storytelling' },
      { id: 'shawn-coyne', name: 'Shawn Coyne', icon: '📊', title: 'Story Grid Creator — Editorial Diagnostics & Genre-Prescriptive Story Craft', whenToUse: 'When diagnosing why a story isn\'t working. When editing scene by scene. When classifying by content genre. When applying the Five Commandments. When analyzing value shifts. When a story needs rigorous structural analysis.', squad: 'storytelling' },
      { id: 'story-chief', name: 'Story Chief', icon: '📖', title: 'Storytelling Squad Orchestrator — Narrative Intelligence Router', whenToUse: 'When a user needs storytelling help but isn\'t sure which specialist to consult. When multiple narrative frameworks need integration. When routing storytelling requests across domains.', squad: 'storytelling' },
    ]
  },
  {
    id: 'traffic-masters',
    name: 'Traffic Masters',
    icon: '📢',
    agents: [
      { id: 'ad-midas', name: 'Ad Midas', icon: '✨', title: 'Ad Creative Strategy & Production Specialist', whenToUse: 'When creating ad creatives. When ads aren\'t getting clicks. When needing ad scripts, concepts, or creative briefs. When testing creative angles. When building creative libraries.', squad: 'traffic-masters' },
      { id: 'ads-analyst', name: 'Ads Analyst', icon: '🔎', title: 'Ad Account Audit & Optimization Specialist', whenToUse: 'When auditing an ad account. When performance is declining without clear cause. When taking over an existing account. When looking for wasted spend. When optimizing account structure.', squad: 'traffic-masters' },
      { id: 'creative-analyst', name: 'Creative Analyst', icon: '🔬', title: 'Ad Creative Performance Analysis Specialist', whenToUse: 'When analyzing which ad creatives work best. When identifying creative patterns. When building creative testing frameworks. When creative is fatiguing. When optimizing ad creative strategy.', squad: 'traffic-masters' },
      { id: 'depesh-mandalia', name: 'Depesh Mandalia', icon: '📐', title: 'The BPM Method Creator — Facebook Scaling Architect', whenToUse: 'When scaling Facebook/Meta ads from 5 to 6-7 figures. When applying the BPM Method. When CBO campaigns need structure. When testing audiences and creatives systematically. When building full-funnel Facebook architecture.', squad: 'traffic-masters' },
      { id: 'fiscal', name: 'Fiscal', icon: '💰', title: 'Ad Budget & Financial Management Specialist', whenToUse: 'When setting ad budgets. When managing cash flow for advertising. When calculating ROAS targets. When planning budget scaling. When assessing ad spend profitability.', squad: 'traffic-masters' },
      { id: 'kasim-aslam', name: 'Kasim Aslam', icon: '🔍', title: 'Google Ads Authority — Solutions 8 Founder & \'You vs. Google\' Author', whenToUse: 'When running Google Ads. When optimizing Performance Max campaigns. When setting up Google Search, Shopping, or Display. When the adversarial \'You vs. Google\' framework applies. When scaling Google ad spend.', squad: 'traffic-masters' },
      { id: 'media-buyer', name: 'Media Buyer', icon: '🖥️', title: 'Cross-Platform Media Buying & Campaign Execution', whenToUse: 'When setting up ad campaigns. When managing daily optimization. When structuring campaigns. When choosing bid strategies. When managing multi-platform campaigns.', squad: 'traffic-masters' },
      { id: 'molly-pittman', name: 'Molly Pittman', icon: '👑', title: 'The Conversion Queen — Facebook Ads Strategist & Traffic System Builder', whenToUse: 'When building Facebook/Meta ad systems from scratch. When structuring ad campaigns with the Ad Grid. When applying traffic temperature strategy. When scaling e-commerce or info product traffic. When training media buyers.', squad: 'traffic-masters' },
      { id: 'nicholas-kusmich', name: 'Nicholas Kusmich', icon: '🎯', title: 'Contextual Congruence Pioneer — High-ROI Facebook Strategist', whenToUse: 'When Facebook ads need to feel native, not interruptive. When applying the Give-Give-Give-Ask philosophy. When targeting the 4% hyper-specific avatar. When building high-ROI campaigns for coaches, consultants, and personal brands.', squad: 'traffic-masters' },
      { id: 'pedro-sobral', name: 'Pedro Sobral', icon: '🥷', title: 'O Ninja Supremo do Tráfego — Gestor de Tráfego Pioneer', whenToUse: 'When managing traffic for Brazilian/LATAM markets. When training gestores de tráfego. When applying Meta Ads in Portuguese-speaking markets. When systematic ad testing and optimization is needed. When building traffic management as a profession.', squad: 'traffic-masters' },
      { id: 'performance-analyst', name: 'Performance Analyst', icon: '📊', title: 'Campaign Data Analysis & Reporting Specialist', whenToUse: 'When analyzing campaign performance. When building dashboards. When determining what\'s working and what isn\'t. When reporting to stakeholders. When making data-driven decisions.', squad: 'traffic-masters' },
      { id: 'pixel-specialist', name: 'Pixel Specialist', icon: '🔌', title: 'Tracking, Pixels & Attribution Specialist', whenToUse: 'When tracking isn\'t working. When conversion data is inaccurate. When setting up pixels. When dealing with iOS/privacy changes. When attribution is unclear. When implementing server-side tracking.', squad: 'traffic-masters' },
      { id: 'ralph-burns', name: 'Ralph Burns', icon: '🎙️', title: 'Performance Marketing Pioneer — Tier 11 & Perpetual Traffic', whenToUse: 'When building full-funnel paid social strategies. When nCAC and MER analysis is needed. When applying the Five Levels of Traffic framework. When creative strategy needs The Creative Lab approach. When scaling purpose-driven businesses.', squad: 'traffic-masters' },
      { id: 'scale-optimizer', name: 'Scale Optimizer', icon: '🚀', title: 'Campaign Scaling & Efficiency Specialist', whenToUse: 'When scaling ad spend. When CPA increases with budget. When experiencing diminishing returns. When planning budget increases. When expanding to new audiences or platforms.', squad: 'traffic-masters' },
      { id: 'tom-breeze', name: 'Tom Breeze', icon: '🎬', title: 'The YouTube Ads Authority — ADUCATE Formula & Viewability Pioneer', whenToUse: 'When running YouTube ads. When writing video ad scripts. When building YouTube ad funnels. When applying intent-based advertising. When TrueView or in-stream campaigns need optimization.', squad: 'traffic-masters' },
      { id: 'traffic-chief', name: 'Traffic Chief', icon: '🎯', title: 'Traffic Masters Orchestrator', whenToUse: '', squad: 'traffic-masters' },
    ]
  },
];

export const AGENTS: Agent[] = SQUADS.flatMap(s => s.agents);

export const ROUTING_GUIDE = AGENTS.map(a =>
  `- ${a.id} (${a.name} ${a.icon}): ${a.whenToUse}`
).join('\n');
